### ISSUE TITLE
WARNING: No tags with type Molecule in data (-uniqueTagCount Molecule)

### ISSUE THREAD

**Issue by malonzm1** [milaboratory/mixcr#1079]
Hi,

When I run mixcr, I get this warning:

WARNING: No tags with type Molecule in data (-uniqueTagCount Molecule)

Can this be caused by incorrectly running mixcr?

Thanks and good day.

**Comment by mizraelson** [comment]
Hi, can you please share the commands you used?

**Comment by malonzm1** [comment]
Hi, thanks.

```mixcr analyze smartseq2-vdj-full-length -s hsa hsa --rna --threads 4  --force-overwrite SRR6155081_pass_{{CELL0ROW:a}}_1.fastq.gz SRR6155081_pass_{{CELL0ROW:a}}_2.fastq.gz```

**Comment by mizraelson** [comment]
I see, in that case that warning is fine, we will fix it. There are no UMIs in SmartSEQ2 protocol, but in export there is a parameter that suppose to export UMI count. That shouldn't affect the analysis.

Btw, do you work with the data that you have shared in another [issue](https://github.com/milaboratory/mixcr/issues/1073#issuecomment-1512379130)? I have checked the article and as far as I understand they don't use the original SmartSEQ2 protocol, but another version - [CEL-seq](https://www.cell.com/cell-reports/fulltext/S2211-1247(12)00228-8?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2211124712002288%3Fshowall%3Dtrue), which has cell barcodes in the read, so the data is pooled together, that's why there is only one pair of files. We don't have a ready preset for this protocol yet, but will add it soon.

**Comment by malonzm1** [comment]
Thanks! I actually used the same data but I used --split-files with fastq-dump to generate multiple files. I suppose this was not the correct approach. I'll wait for the preset for CEL-seq then. 

I took a look at another smart-seq2 dataset. According to this https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&acc=SRR8466396&display=data-access the original files submitted is just 2 (paired). Will this not work either?

**Comment by mizraelson** [comment]
Hi, the smart-seq2 protocol implies that cells are sorted in different wells and are barcoded with Illumina adapters, thus bcl2fastq should produce a pair of files for every well/cell.
According to the publication:
"Multiplex sequencing of 96 single-cell libraries was performed on a Hiseq 1500 lane in 150-bp paired-end mode, giving an average sequence depth of 2 million reads per cell.". 
This [link](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE127969&format=file&file=GSE127969%5FcellID%5Fbarcode%5FSRR%2Etxt%2Egz), as I understand, shows Illumina barcode pairs for every sample. But then it's not clear where are the Index reads to de-multiplex the data.

**Comment by malonzm1** [comment]
Hi again,

Sorry if this is obvious, but what does the warning "WARNING: No tags with type Molecule in data (-uniqueTagCount Molecule)" mean?

**Comment by malonzm1** [comment]
When I use the generic preset rnaseq-full-length I am able to generate clonotypes but not when I use the smart-seq2 preset smartseq2-vdj-full-length. I wonder why.
