### ISSUE TITLE
Alignment failed, no hits (not TCR/IG?)

### ISSUE THREAD

**Issue by zznx** [milaboratory/mixcr#1137]
Hi,
I wonder if it's possible to identify these unidentified clone sequences? What causes this?
`Alignment failed, no hits (not TCR/IG?): 285668 (74.99%)`

Thanks
## MiXCR report files 

Analysis date: Wed Jun 07 21:22:16 CST 2023
Input file(s): result70/IGHV_CLLB0206-IGHV_S22_L001_R1_001.fastq/CLLB0206-IGHV_S22_L001_clean_R1_001.fastq.gz,result70/IGHV_CLLB0206-IGHV_S22_L001_R1_001.fastq/CLLB0206-IGHV_S22_L001_clean_R2
Output file(s): result70/IGHV_CLLB0206-IGHV_S22_L001_R1_001.fastq/CLLB0206-IGHV_S22_L001_align.vdjca
Version: 3.0.13; built=Wed Apr 15 23:28:14 CST 2020; rev=f614226; lib=repseqio.v1.6
Command line arguments: align -s human -p kAligner2 -t 16 -f -OminSumScore=200 --library imgt.201946-3.sv6.json -OsaveOriginalReads=true --report result70/IGHV_CLLB0206-IGHV_S22_L001_R1_001.f
Analysis time: 1.72m
Total sequencing reads: 380964
Successfully aligned reads: 81177 (21.31%)
Paired-end alignment conflicts eliminated: 20273 (5.32%)
Alignment failed, no hits (not TCR/IG?): 285668 (74.99%)
Alignment failed because of absence of V hits: 8283 (2.17%)
Alignment failed because of absence of J hits: 3567 (0.94%)
No target with both V and J alignments: 2269 (0.6%)
Overlapped: 288532 (75.74%)
Overlapped and aligned: 61 (0.02%)
Alignment-aided overlaps: 5 (8.2%)
Overlapped and not aligned: 288471 (75.72%)
V gene chimeras: 8322 (2.18%)
J gene chimeras: 4 (0%)
IGH chains: 81175 (100%)
IGL chains: 2 (0%)
Realigned with forced non-floating bound: 184874 (48.53%)
Realigned with forced non-floating right bound in left read: 188 (0.05%)
Realigned with forced non-floating left bound in right read: 188 (0.05%)

**Comment by mizraelson** [comment]
Hi, yes, generally this means that these reads did not align with any (TCR or BCR) reference sequences. You can export these reads in a separate FASTQ files and manually examine using BLAST adding these parameters to align command:

`--not-aligned-R1 not-aligned_R1.fastq`
`--not-aligned-R2 not-aligned_R2.fastq`

Also, I have noticed you are using an old version of MiXCR. I would highly recommend updating, since almost all algorithms have been improved drastically since version 3.0.13.

**Comment by zznx** [comment]
Thanks I will try the latest version
