### ISSUE TITLE
Updating miXCR pipeline to current version

### ISSUE THREAD

**Issue by abyappan** [milaboratory/mixcr#1293]
Hi,

I am trying to use a miXCR pipeline published in a STAR protocols paper: [Localization of T cell clonotypes using the Visium spatial transcriptomics platform](https://www.sciencedirect.com/science/article/pii/S2666166722002714). Their paper data and code can be found here: https://github.com/whhudson/spatialTCR

The pipeline uses miXCR v3.0.13. I am trying to update this to run on v4.4.2. 

When I run the pipeline on v.4.4.2, I receive the following error message:
`Unknown options: '--starting-material', '--align', '-OsaveOriginalReads=true', '--assemble', '--write-alignments', 'pt16_downsample_L001_R2_001.fastq.gz', 'mixcr_output_v4.4.2/clones'
Possible solutions: --strict-sample-sheet-matching`

The exact code I ran:
`mixcr analyze shotgun -s hsa --starting-material rna --align "-OsaveOriginalReads=true" --assemble "--write-alignments" pt16_downsample_L001_R2_001.fastq.gz mixcr_output_v4.4.2/clones`

Would you be able to help me update the code?

**Comment by mizraelson** [comment]
Hi, please use the command below:

```
mixcr analyze rna-seq \
    --species hsa \
      input_R1.fastq.gz \
      input_R2.fastq.gz \
      result
```

**Comment by abyappan** [comment]
Hi, thank you for your response. What is the difference in the "old" code between `--align "-OsaveOriginalReads=true"` and `--assemble "--write-alignments"`? When the old code was run, a folder named "reads" would contain fastq.gz files for each clonotype identified and I am trying to recreate that.

**Comment by mizraelson** [comment]
Hi,
In the old version of MiXCR:
- The `--align "-OsaveOriginalReads=true"` parameter preserves the original reads, so it is possible to export them back later. I'm not sure why the authors use this one.
- The `--assemble "--write-alignments"` parameter saves alignments to a .clna file (instead of just saving clones). This parameters makes it possible to use `exportReadsForClones` later.

I took a closer look at the protocol, and actually, the new MiXCR can handle this data much better now. In the past, MiXCR couldn't work with barcodes (such as spatial barcodes or UMIs), which is why the authors were exporting the reads from the clones to match them to the barcodes using a python script. The latest version of MiXCR can handle the full pipeline without the need to export the reads.

The command below will perform UMI correction and filtering and produce clonotype tables with a spatial (cell) barcode and UMI count for every clone.

```
mixcr analyze generic-ht-single-cell-amplicon-with-umi \
    --species hsa \
    --rna \
    --floating-left-alignment-boundary \
    --rigid-right-alignment-boundary C \
    --tag-pattern "^(CELL:N{16})(UMI:N{12})\^(R2:*)" \
    input_R1.fastq.gz \
    input_R2.fastq.gz \
    result
```

Also, to enhance barcode correction you can use a whitelist for spatial barcodes. Please find the file attached. I have accumulated all variants for all [serial numbers](https://kb.10xgenomics.com/hc/en-us/articles/360041426992-Where-can-I-find-the-Space-Ranger-barcode-whitelist-and-their-coordinates-on-the-slide-).

```
mixcr analyze generic-ht-single-cell-amplicon-with-umi \
    --species hsa \
    --rna \
    --floating-left-alignment-boundary \
    --rigid-right-alignment-boundary C \
    --tag-pattern "^(CELL:N{16})(UMI:N{12})\^(R2:*)" \
    --set-whitelist CELL=file:spatial_barcodes.txt \
    input_R1.fastq.gz \
    input_R2.fastq.gz \
    result
```

However, it's worth noting, I have downloaded the data from the original publication, and I see the protocol is very unspecific. Most of the reads (95%) do not contain TCR or BCR sequences. I assume it's due to the primer-multiplex nature of it. Usually, V-gene multiplex is used after C gene targeting, but here all polyA RNAs are targeted, and no enrichment is performed except for the large amount of primers that end up amplifying a lot of unspecific products.

Also, the command used in the paper is not really correct as it is designed for fragmented data (e.g., shotgun sequencing) while the reads according to the library structure rather resemble amplicon sequencing, where every read (theoretically) should always cover an entire CDR3 region. Just in case you would want to use their script, below you can find the commands adapted for the new MiXCR version, but I don't recommend doing that, as MiXCR uses sophisticated algorithms to correct and filter erroneous barcodes instead of just assigning and counting them.

```
mixcr analyze generic-amplicon \
    --species hsa \
    --rna \
    --floating-left-alignment-boundary \
    --rigid-right-alignment-boundary C \
    -Malign.parameters.saveOriginalReads=true \
    -Massemble.clnaOutput=true \
    input_R2.fastq.gz \
    result

mixcr exportReadsForClones \
    -s \
    input.clna \
    reads.fastq.gz
```

Let me know if that makes sense and if you have any other questions!
Sincerely,
Mark
[spatial_barcodes.txt](https://github.com/milaboratory/mixcr/files/12284344/spatial_barcodes.txt)

**Comment by abyappan** [comment]
Thank you so much for this very helpful explanation! It makes sense, and I truly appreciate your time and help.
