### ISSUE TITLE
Error in generating plot for "Gini coefficient"

### ISSUE THREAD

**Issue by KashingTang** [milaboratory/mixcr#1438]
I am using immunarch verison 0.9.0, 
R version 4.3.2 (2023-10-31 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 11 x64 (build 22621)

Using the command " repDiversity" and "vis ", I can generate plots using methods like chao1, hill, div, inv.simp, d50. 
But when I try to use the 'gini' method, I get an error.

## Exact MiXCR commands 

div_gini <- repDiversity(immdata$data, "gini")
vis(div_gini)

## MiXCR report files 

Error in UseMethod("vis") : 
  no applicable method for 'vis' applied to an object of class "c('immunr_gini', 'matrix', 'array')"

**Comment by mizraelson** [comment]
Hi, this issue is not related to MiXCR, but rather to immunarch. If you're looking to calculate and plot diversity metrics, there's no need to rely on any standalone packages, since MiXCR includes capabilities for downstream analysis. You can read more about it [here](https://mixcr.com/mixcr/reference/mixcr-postanalysis/#individual-postanalysis). Please let me know if you have any questions regarding the postanalysis features of MiXCR.

**Comment by KashingTang** [comment]
Thank you for your prompt response and suggestion. 
And sorry for asking in the wrong place. 
I will try the downstream analysis features of MiXCR. Thank you again.
