### ISSUE TITLE
aaFeature differs from aaFeatureFromLeft and aaFeatureFromRight?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#152]
Hello,

I'm trying to understand how the aaFeature CDR3 field is derived.  I have RNA-Seq data I aligned using the recommended pipeline.  When I exportClones, I can have it export: -aaFeature CDR3, -aaFeatureFromLeft CDR3, -aaFeatureFromRight CDR3 and the NT sequence.  -aaFeature CDR gives me CVAGGWE_TAQLFF; however, fromLeft and fromRight both give me CVAGGWEHRAAVL, which matches the NT sequence translation.  What's different about -aaFeature?  I assume the underscore is telling me there's a disagreement or missing data?  Thanks for any help.

**Comment by dbolotin** [comment]
Thanks for pointing on it! There is a bug in -aaFeatureFromRight , it actually outputs exactly the same sequence as -aaFeatureFromLeft . This will be fixed in upcoming 2.0.1 . Sorry for the inconvenience.

Please see the following file, it contain explanation of translation algorithms used in `-aaFeature*` columns:
https://github.com/milaboratory/milib/blob/develop/src/main/java/com/milaboratory/core/sequence/AminoAcidSequence.java#L293

I also want to change the output for these columns to include incomplete codon in case of out-of-frame sequences, while in current version it is just skipped (roughly, translation is performed using `translateFromLeft` / `translateFromRight` methods from the file I mentioned, and '_' symbol is just removed). It would be great to know your opinion on weather this 'more verbose' output will be more convenient for users.

Thanks!
