### ISSUE TITLE
MiXCR Default Library

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1586]
Hello, 

I had a question regarding the MiXCR's defaut library reference sequences. I noticed there were some differences in terms of list of alleles for specific v genes and what v genes were included in the reference sequences. Could you elaborate little more on how the default library was built?

Also, if i would want to compare the scTCR output from cell ranger with bulk TCR output from MiXCR to do clonotype expansion tracking over time, how would you recommend synchronizing the reference sequences?

**Comment by mizraelson** [comment]
1) The MiXCR library is based on genomic information and does not include alleles directly. To infer alleles from the data, there is a dedicated function,[`mixcr findAlleles` ](https://mixcr.com/mixcr/reference/mixcr-findAlleles/). This method is considered more reliable because, in many other databases, hypermutations and sequencing/PCR errors are often mistakenly identified as alleles. 

2) I recommend comparing different approaches by mapping the actual VDJ region nucleotide sequence, as the sequence should remain consistent regardless of the allele identification.
