### ISSUE TITLE
Mixcr to VDJtools

### ISSUE THREAD

**Issue by pbpayal** [milaboratory/mixcr#1616]
## takara-mouse-rna-bcr-smarter
I used this module to generate results from Mixcr. 

## Exact MiXCR commands 

``mixcr analyze takara-mouse-rna-bcr-smarter 1B_fastq_R1.gz  1B_fastq_R2.gz result_1B``

### Import into VDJtools
I want to further investigate the results using VDJtools. 
*Which output file to use for vdjtools? Is it the .clns file or .tsv files? 
*Do I need to convert the file for VDJtool usage? 
*I tried both convertion and using the .tsv file as is in VDJtools. It gives me error.

### Actual Result Files
result_1B.align.report.basicstats.txt
result_1B.align.report.json
result_1B.align.report.txt
result_1B.assemble.report.json
result_1B.assemble.report.txt
result_1B.clns
result_1B.clones_IGH_nondecimal.tsv
result_1B.clones_IGH_nondecimal.txt
result_1B.clones_IGH.tsv
result_1B.clones_IGK.tsv
result_1B.clones_IGL.tsv
result_1B.qc.json
result_1B.qc.txt
result_1B.vdjca

### VDJ command Convert for TSV file
*````
java -Xmx4g -jar $VDJ_JAR Convert -S mixcr result_1B.clones_IGH.tsv result_1B.clones_IGH ````*

### Head of output TSV file (IGH)

*````cloneId	readCount	readFraction	targetSequences	targetQualities	allVHitsWithScore	allDHitsWithScore	allJHitsWithScore	allCHitsWithScore	allVAlignments	allDAlignments	allJAlignments	allCAlignments	nSeqFR1	minQualFR1	nSeqCDR1	minQualCDR1	nSeqFR2	minQualFR2	nSeqCDR2	minQualCDR2	nSeqFR3	minQualFR3	nSeqCDR3	minQualCDR3	nSeqFR4	minQualFR4	aaSeqFR1	aaSeqCDR1	aaSeqFR2	aaSeqCDR2	aaSeqFR3	aaSeqCDR3	aaSeqFR4	refPoints
1	207.0	0.350253807106599	GTTGTAATTAGTATCACCATCTCCAGGAAAAATCTGTCCAATCCACTCAAGACCCTTTCCAGGCCTCTGCTTCACCCAGTTCATCCAGTAATTACTGGATGAACTGGGTGAAGCAGAGGCCTGGAAAGGGTCTTGAGTGGATTGGACAGATTTTTCCTGGAGATGGTGATACTAATTACAACGGAAAATTCAAGGACAAGGCCACACTGACTGCAGACAAATCCTCCAACACAGCCTACATGCAGCTCAGCAGTCTGACCTCTGAGGACTCTGCGGTCTATTTCTGTGCAAGAGGCGGCTACTGGGGCCAAGGCACCACTCTCACAGTCTCCTCAG	[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[	IGHV1-80*00(676)		IGHJ2*00(380)	IGHG3*00(181.7)	77|371|391|0|293|SC77GSA78TSG79TI82AI82ASC83TSC86TST87ASG88TSG91CSG94TI95CST97CSG98ASG101ASC102AST103ASG104ASG106TSG110TST111CSG112CSG115TST118ADG119DG120DG121DG122DC123SG128ADT129SA132CSG133CSA134CST140AI142GI142CSA143TSA144CSA145TST151ASG152CSG153CST155ASA156GSC157TSG158TST162CSG168ASC169TSA231TSC253TSG265ASG273ASG306ASC331T|1199.0		30|68|68|298|336||380.0		GTTGTAATTAGTATCACCATCTCCAGGAAAAATCTGTCCAATCCACTCAAGACCCTTTCCAGGCCTCTGCTTCA	58	CCCAGTTCATCCAGTAATTACTGG	58	ATGAACTGGGTGAAGCAGAGGCCTGGAAAGGGTCTTGAGTGGATTGGACAG	58	ATTTTTCCTGGAGATGGTGATACT	58	AATTACAACGGAAAATTCAAGGACAAGGCCACACTGACTGCAGACAAATCCTCCAACACAGCCTACATGCAGCTCAGCAGTCTGACCTCTGAGGACTCTGCGGTCTATTTC	58	TGTGCAAGAGGCGGCTACTGG	58	GGCCAAGGCACCACTCTCACAGTCTCCTCAG	58	VVISITISRKNL_QSTQDPFQASAS	PSSSSNYW	MNWVKQRPGKGLEWIGQ	IFPGDGDT	NYNGKFKDKATLTADKSSNTAYMQLSSLTSEDSAVYF	CARGGYW	GQGTTLTVSS_	::::0:74:98:149:173:284:0:293:::::298:-10:305:336::````*

### Error
*````
[ERROR] java.lang.RuntimeException: Unable to parse clonotype string 207 for MiXcr input type: Some mandatory columns are absent in the input file.````  *

**Comment by mizraelson** [comment]
Hi,
VDJtools is our legacy software, so we don't support it anymore. The new MiXCR has a slightly new output format that's why `vdjtools` does not recognize it. Most of the [postanalysis](https://mixcr.com/mixcr/reference/mixcr-postanalysis/) function are now included in the MiXCR so you might wanna try using it instead.

Nevertheless, there is a way to manually bypass the issue if needed:
- New MiXCR has columns named : `readCount`, `readFraction` and `uniqueMoleculeCount`, `uniqueMoleculeFraction` (in case of UMIs).  For `vdjtools` to work correctly the following columns are required: `cloneCount`, `cloneFraction`. A simple rename will help. Keep in mind that if you have both reads and UMIs you should pick which one do you wanna use and rename the columns of interest.
- Another thing is `region not covered` field that sometimes is present if gene region was not covered by the alignment. We used to leave these fields blank (if the region was not covered) but that confused some of our users so we added this note.
As a bypass you can run the following command for the `mixcr` tsv output files to remove it:
    `sed -i 's/region_not_covered//g' sample1.tsv`
