### ISSUE TITLE
warning using imgt data

### ISSUE THREAD

**Issue by fabioticconi** [milaboratory/mixcr#169]
I get this warnings with every run:

```
Reference library: imgt.201631-4.sv1:10090 (8c3eb7e7ab2b9c6a427747cfad4eb9c1)
WARNING: Functional gene TRAV6-2*03 doesn't contain full VRegionWithP (excluded)
WARNING: ... 39 more functional genes excluded due to absent "featureToAlign".
```

Is this something intrinsically related to the imgt data, that I can ignore, or is this due to mixcr?

**Comment by dbolotin** [comment]
This warning represents absent part of sequences in functional IMGT's genes. So, yes, it is something intrinsically related to the imgt.

E.g. [here](http://www.imgt.org/IMGTrepertoire/Proteins/alleles/mouse/TRA/TRAV/Mu_TRAV6-2.html) you can see that TRAV6-2*03 doesn't cover beginning of FR1.

In most cases this affects only allelic variants (*02, ...) and can be ignored, but there are cases for some species where main/ref (*01) gene sequences are also partially covered. Because of this, we decided that it is not safe to silently exclude functional sequences without notifying user.

**Comment by fabioticconi** [comment]
Makes sense, thanks for the clarification!
