### ISSUE TITLE
High percentage of alignment failed due to no hits (not TCR/IG?) in 10X TCR data

### ISSUE THREAD

**Issue by genome2020** [milaboratory/mixcr#1753]
Hi 
I have analyzed my 10X TCR repertoire data using the 'analyze' command in MiXCR using the '10x-sc-xcr-vdj' preset. However, I am getting a significant percentage of reads (~15-50%) failing alignment due to 'no hits (not TCR/IG?)'. I aligned the unaligned reads against the hg38 genome and I see a good percentage of these reads mapped to the TCR genes loci. Would you have any suggestions on how I can improve my alignment rate and recover the unaligned reads? 

I am using MiXCR version 4.6.0. 

Here is the command I am using

mixcr -Xmx100g analyze 10x-sc-xcr-vdj --species hsa sample1_R1_001.fastq.gz" smaple2_R2_001.fastq.gz" sample1

**Comment by mizraelson** [comment]
Hi, the command is correct. This sometimes happens if you have many reads covering only the C gene. MiXCR reports such reads as non-target because it looks for reads that at least partially cover the V, J, or D genes. If you can share the data, I can take a look and confirm. You can send it to support@milaboratories.com.
