### ISSUE TITLE
Overlapped and aligned: 

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#237]
Our BIOMED-2 protocol based BCR analysis shows Overlapped and not aligned: 1138271 (66%)
I would like to know what could potentially make the overlapped reads couldn't be aligned.

Thanks!

> ======================================
> Command line arguments: align --chains ALL --species hsa -OallowPartialAlignments=true --report BCR01-02.alignmentReport.log BCR01-02_R1.fq.gz BCR01-02_R2.fq.gz BCR01-02.alignment.vdjca
> Total sequencing reads: 1724739
> Successfully aligned reads: 424966 (24.64%)
> Chimeras: 1 (0%)
> Alignment failed, no hits (not TCR/IG?): 62 (0%)
> Alignment failed because of absence of CDR3 parts: 859967 (49.86%)
> Alignment failed because of low total score: 439744 (25.5%)
> Overlapped: 1480527 (85.84%)
> Overlapped and aligned: 342256 (19.84%)
> Overlapped and not aligned: 1138271 (66%)
> TRA chains: 17 (0%)
> TRB chains: 244 (0.06%)
> TRG chains: 1 (0%)
> IGH chains: 411470 (97.1%)
> TRA,TRD chains: 1 (0%)
> IGK chains: 11754 (2.77%)
> IGL chains: 263 (0.06%)
> ======================================

**Comment by dbolotin** [comment]
There are millions of possible experimental / processing artefacts, each time something goes wrong it goes wrong in a new way. The easiest way to understand why any downstream NGS analysis produce unexpected results is to manually examine the data, especially if software tells you that more than 50% of input reads are affected. Inspection of only five PE-reads in such situation will give you 31/32 chance to catch the problematic read!

Sorry, but interpretation of problems that are not verified to be a result of wrong MiXCR behaviour is out of the scope of this issue tracker.

If you think that problem is in the software, please isolate several reads for which you believe MiXCR should produce different alignments / clonotypes assembly, and provide detailed description on how reproduce the result.

**Comment by suntaosimon** [comment]
Thanks so much. 
I am sorry that maybe I did not express myself well. I did not mean there might be any problems in the software. I know there must be something wrong either with the library preparation or the sequencing errors.
 
Actually, the reason I opened this issue is that I want to understand what dose "Overlapped and not aligned" mean, in order to find any of  my experiments problems.  Please tell me if my understanding is right,
"Overlapped"means paired-end reads fastq files have been processed into one file (connect 2 reads together)?
"not aligned" means the raw sequencing reads can to be mapped to reference V, D, J and C genes of T- and B- cell receptors?
