### ISSUE TITLE
Add verbose error message for wildcard-containing reference sequences

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#260]
And add command-line option to exclude them from analysis, if user still wants to analyse data using given reference library.

**Comment by bbimber** [comment]
Hi Dmitry - attached is one possible solution.  A gene where the feature has wildcards is essentially the same thing as a gene without that feature (from the aligner's perspective).  ActionAlign already has code to iterate all genes and only includes that gene if VDJCAlignerParameters.containsRequiredFeature() is true.  It would be easy to extend that method to also check for wildcards.  I'd argue this is essentially in the spirit of how MiXCR already behaves, just a more thorough check.

It might be nice to separately log genes that fail due to lack of feature from those failing due to wildcards.  If you think that's important i'm happy to extend this to do that.  

Attached is a patch.  if you think this is viable i'll put in a pull request.
[Wildcards.patch.txt](https://github.com/milaboratory/mixcr/files/1200342/Wildcards.patch.txt)
