### ISSUE TITLE
about the parameter of OjParameters.parameters.absoluteMinScore 

### ISSUE THREAD

**Issue by wangyingzhen** [milaboratory/mixcr#286]
[Jscore40.vdjca.txt](https://github.com/milaboratory/mixcr/files/1504647/Jscore40.vdjca.txt)
[Jscore5.vdjca.txt](https://github.com/milaboratory/mixcr/files/1504892/Jscore5.vdjca.txt)

hi, i am Yingzhen Wang. I have ask some question through email.Thanks for your reply.And i accept your advice, post the question on github. 
About the question3 in email, I want to know why the read id 4 in Jscore5.vdjca.txt( -OjParameters.parameters.absoluteMinScore=5) was dropped when i use the  parameter -OjParameters.parameters.absoluteMinScore=40(in Jscore40.vdjca.txt);  Although the Target0 align TRBJ2-7*00 score is 15(<40), but the score of Target1 is 96 (>40).  The same of read id 2 , read id 5 and so on in Jscore5.vdjca.txt, which meet the criteria(score>=40 ), but can not found in Jscore40.vdjca.txt.
As your reply,  they were dropped  at assembly because they doesn’t contain CDR3. In deed, they were dropped at align. So i am puzzled.

Best,
Yingzhen Wang

**Comment by dbolotin** [comment]
Hi,

MiXCR has two alignment rounds: (1) very fast that detects relatively long alignments (2) if first round was successful for one read (in read-pair) and not successful for another, it tries to align not aligned mate with very accurate algorithm against genes that were found in the first round.

The threshold for the alignment in the second round equals to `absoluteMinScore`.

MiXCR accepts only VDJC alignments having both V and J genes in one of the mate pairs.

So, in your case, the following happens with read 4:

* absoluteMinScore=5
  * V gene aligned in first mate
  * J gene aligned in the second mate
  * Second round of alignment is performed for the first mate and `TRBJ2-7*00`
  * Alignment from the second round is **accepted** because 15 > 5
  * MiXCR **accepts** alignment as a whole as having V and J genes in the first read (`Target0`)

* absoluteMinScore=40
  * V gene aligned in first mate
  * J gene aligned in the second mate
  * Second round of alignment is performed for the first mate and `TRBJ2-7*00`
  * Alignment from the second round is **dropped** because 15 < 40
  * MiXCR **drops** alignment as a whole as not having both V and J genes in any of reads

**Comment by PoslavskySV** [comment]
BTW, if you want to preserve partial alignments (only V or only J), you can use -OallowPartialAlignments=true, see http://mixcr.readthedocs.io/en/latest/rnaseq.html

**Comment by wangyingzhen** [comment]
Thank you for the info, I will follow your suggestion.
