### ISSUE TITLE
WARNING: 104 functional genes were excluded, re-run with -v option to see the list of excluded genes and exclusion reason.

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#330]
WARNING: 104 functional genes were excluded, re-run with -v option to see the list of excluded genes and exclusion reason.

When process mouse RNA TCR data with default Alignment command, and it shows this warning. What dose this mean? Isn't "-v" a checking version option?

**Comment by suntaosimon** [comment]
I guess it's because of the library. 
When I re-process the data with imgt.201748-3.sv2 library, the warning changes to 86 functional genes were excluded. 
So, there is no 100% covered library?

**Comment by dbolotin** [comment]
Hi,

1. Sorry for the misleading warning message, it actually is:
`re-run with --verbose option to see the list of excluded genes and exclusion reason.`
not `-v`, it is [already fixed](https://github.com/milaboratory/mixcr/commit/a2bbefaae252a7262a982700cf6d3ea2b1589b1d#diff-a862c09aaf24b00889ff906212ad68f1L89), will be released in 2.1.9.

2. Warnings for murine library are nearly all connected to IGs (the only affected TR gene is TRGV2*00). We are actively working on the library for the subsequent release, so, I hope, even for IGs it will be nearly perfect in 2.1.9.

3. Unfortunately IMGT library inherently lacks important gene parts (like 5'UTRs, and L1) for many records. Because IMGT library is not entirely based on genomic sequences (as repseqio library) there is nothing much that can be done to fix it. As a workaround you can use `-OvParameters.geneFeatureToAlign=VRegion` in case of `-p rna-seq`, this will limit target part of V genes for alignments to `VRegion`, which is present in most of IMGT records, though it will reduce data yield for e.g. RNA-Seq data.
