### ISSUE TITLE
Reads dropped due to the lack of clone sequence

### ISSUE THREAD

**Issue by Lucianabarros** [milaboratory/mixcr#335]
Hi MiXCR team,

It's more a question than an issue. I analyzed RNA-seq data to get TCR sequences. MiXCR usually works fine for Illumina output, but this time I'm analyzing ION TORRENT data. The alignment was ok, and I ran assemble partial, then assemble. I lost almost all my reads due to this message: "Reads dropped due to the lack of a clone sequence: ". Is it an absence of CR3 parts? What it means and how can I solve this?

Thanks in advance,
Luciana

**Comment by PoslavskySV** [comment]
Yes, that mean the absence of CDR3 parts. There are many possible reasons for this (most of them are due to the library preparation, i.e. it really badly cover CDR3). Could you please attach all exact commands you used, align report, assemblePartial  report and assemble report? It is also useful to inspect manually few of your alignments to understand how reads cover VDJ region. For that, could you paste the result of the following command:

```bash
mixcr exportAlignmentsPretty -s 1000 -n 10 you_alignments_file.vdjca
```

**Comment by Lucianabarros** [comment]
Hi,
the commands are as follow:
align: $MIXCR/mixcr align $FASTQ_DIR/$i.fastq $OUTPUT --save-description -f -t $NT -p rna-seq -OallowPartialAlignments=true -r $REPORT 
assemble_partial1: $MIXCR/mixcr assemblePartial -f -r $REPORTN $INPUTN $RESCUEDN1
assemble_partial2: $MIXCR/mixcr assemblePartial -f -r $REPORTN $RESCUEDN1 $RESCUEDN2
assemble: $MIXCR/mixcr assemble --index $index_file_N -f  $RESCUEDN2 $CLONE_N
The pretty file is this (all those reads contain the CDR3 sequence). 
[demo_pretty_alignments.txt](https://github.com/milaboratory/mixcr/files/1700411/demo_pretty_alignments.txt)

Thanks for your help!

**Comment by PoslavskySV** [comment]
Sorry for delayed reply. I just looked your ``demo_pretty_alignments.txt``. In that file, those alignments that lack clonal sequence, really lack clonal sequence (you can check it with e.g. (ig)BLAST). So I conclude that the reason of large amount of dropped reads is in your data, but not in the program.
