### ISSUE TITLE
Question: alignment/clone report differences between v2.1.9 and v2.0.2 -- chain percentage & definition of alignment stats

### ISSUE THREAD

**Issue by xww52526** [milaboratory/mixcr#363]
Hello,

I updated MiXCR to current version v2.1.9 and noticed several changes in alignment/clone report =, in comparison with v2.0.2.
Particular, when using v2.0.2, in the alignment report and clone report, chain composition percentage would be reported, for example, 

for TCR:
`[TRA]chains: 1 (7.69%)
[TRB] chains: 12 (92.31%)
`

For IG:
`
[IGH] chains: 74   (0.01%)
[IGK] chains: 5 (0%)
[IGL] chains: 682415 (99.99%)
`

In v2.1.9, this feature seems is disabled? Is it true? Could I adjust some parameters to have chain percentage reported?

Could you also explain definition of “Paired-end alignment conflicts eliminated”, “Alignment-aided overlaps” and “Number of reads used as a core”?  I didn't find their definition in the manual. But feel it would be very helpful for me to understand the results and clarify some confusion I had.

Thanks very much!

**Comment by dbolotin** [comment]
This will be fixed in 2.1.10. Sorry for inconvenience.

`Alignment-aided overlaps` - if two reads was aligned against same, say, V gene (which is the most common case in all setups), after alignment MiXCR may see that same nucleotides (positions in reference sequence) were aligned in both cases. This is a strong evidence that paired-end reads actually overlap, so mixcr merges them into single sequence basing on this new information. This helps to merge PE-reads overlapping even by single nucleotide.

`Paired-end alignment conflicts eliminated` - during the process described above there is a certain check on sequence equality in overlapping region, if it is not met, merge is aborted. Another part of the information MiXCR gains from this event, is that certain paradoxical condition is found, this may be a sign of false-positive alignment in one of the PE reads. In this case MiXCR drops one of the alignments to prevent possible false-positive to somehow spoil downstream processing.

`Number of reads used as a core` number of reads in clonotypes before clustering and low-quality sequence rescue steps (see Supplementary Note 3 in our [original paper](https://www.nature.com/articles/nmeth.3364)).

**Comment by dbolotin** [comment]
Closed with #358
