### ISSUE TITLE
Identification of shortCDR3

### ISSUE THREAD

**Issue by PBarennes** [milaboratory/mixcr#365]
Hi,

We see a problem for the identifying of the shortCDR3, but as you can see on the table (attached)
we have a CDR3 ("long").
Could you explain to me why MiXCR did not detect the shortCDR3 ?

Thank you,

Pierre

![capture d ecran 2018-03-14 a 09 56 02](https://user-images.githubusercontent.com/36883486/37392396-4fe9782e-276e-11e8-848e-0f1f9f43b76f.png)

**Comment by dbolotin** [comment]
MiXCR determines positions of anchor points by their aligned projections from corresponding reference genes.

ShortCDR3 starts from the position CDR3Begin+3 and ends with CDR3End-3 (here +-3 stands for offset in nucleotides, counted relative to reference sequence).

If corresponding position in reference gene is not aligned with the target sequence, MiXCR cant' calculate its position in the target sequence.

In this particular case it seems that only one or two (or even zero) J nucleotides were aligned inside CDR3 ("long") (presumably J gene was trimmed too much during VDJ recombination).

This issue seems to be somehow connected with your previous problem #357, but I dont' see how exactly.

P.S. Main rationale of such position calculation algorithm is to take into account indels in alignments which nontrivially offsets positions of reference sequences relative to target read sequence.
