### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by graingert** [milaboratory/mixcr#382]
Currently mixcr is all setup to be hosted on Maven: https://github.com/milaboratory/mixcr/blob/develop/pom.xml#L34

But it has not yet been published.

https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.milaboratory%22

**Comment by dbolotin** [comment]
Sorry, but due to the license restrictions MiXCR will not be published to Maven.
Basic functionality (aligners, prefix trees, IO, etc..) on which MiXCR is based, is licensed under Apache License (see [MiLib](https://github.com/milaboratory/milib)) and published to [Maven](https://mvnrepository.com/artifact/com.milaboratory/milib).

**Comment by graingert** [comment]
@dbolotin ah I see, would it be possible to publish to bintray instead?

Eg: https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html
