### ISSUE TITLE
Amino acid mutations/alignments with reference genes

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#4]
From this letter:

_Oh well. One more question about the mutations: these are interpretable as SHM, right? Assuming there is not sequencing/pcr error, so NGS being completely error-free, then these mutations would be SHM, and, not as it is now the case a mixture of SHM and NGS-related errors, right? And a suggestion:  it would be nice to have them also on the amino acid levels (similar to IMGT)._

**Comment by mikessh** [comment]
Complex issue. For example how to report two consequent substitutions, which are only non-synonymous when present together. Either report them as synonymous or allow to aggregate mutations (milib)

**Comment by dbolotin** [comment]
I'm thinking about simplest algorithm:
* Translate mutated sequence
* Enumerate substitutions between mutated and germline sequences

```

ATTAAGACACAGATA
|||| ||||| ||||
ATTATGACACCGATA

->

ATTAAGACACAGATA
 I  K  T  Q  I
 |     |     |
 I  M  T  P  I
ATTATGACACCGATA

->

SK1M, SQ3P

```

Exceptional cases:
* If sequence contain long (~ >15 nt) region with shifted frame, don't output mutations, just print something like (`frameshift`)
* But if region is not too long (like the following), still print mutations for it.
```

ATTAAGACACA-GATA
ATTA-GACACATGATA

->

ATTAAGACACAGATA
 I  K  T  Q  I
 |           |
 I  R  H  M  I
ATTAGACACATGATA

->

SK1R, ST2H, SQ3M

```
* For deletions of 3,6,9... nucleotides there is also possible to output amino acid deletions... But it is not so simple in general case

**Comment by dbolotin** [comment]
Basic feature for this is already implemented in com.milaboratory.core.mutations.MutationsUtil.nt2aa()...

**Comment by swuecho** [comment]
"it is now the case a mixture of SHM and NGS-related"  

NGS error should be negligible compared with shm, since 'the mutation occur at a rate of about one muation per V-region" ?

I am trying to calculated SHM using mixcr.

I use the command 

`
mixcr exportClones -vHit -jHit -dHit -count -aaFeature CDR3 -vAlignment -jAlignment 
`

to export the clone with v j alignment, and calculate the mutation based on alignment. but the shm result is very different from what I get using igblast. (we are switching from igblast to mixcr)

Am I in the right direction?  Thanks.

of course, if the shm can be exported directly, it will be great.
