### ISSUE TITLE
FR4 alignments

### ISSUE THREAD

**Issue by nathaniel-jd** [milaboratory/mixcr#403]
I am using MIXCR (v2.1.11, repseqio v1.5) to align full length sequences and have noticed that even in the case of perfect alignments, the FR4 region is often not divisible by 3 (i.e. the translation will produce an incomplete codon). 

An example of this is the alignment of TRAJ36 with TRAC - the FR4 region is 31 nucleotides long and therefore cannot be properly translated.

Is this by design or do the anchor points need shifting?

**Comment by dbolotin** [comment]
Hi, this behaviour is by design. FR4End is defined as the last J gene nucleotide, and the last J gene nucleotide is second nucleotide in a triplet, it takes one more nucleotide from C gene to fulfill it.
You can remove last two nucleotides from the sequence to get "in-frame" sequences by using the following gene feature: `FR4(0,-2)`, e.g.:
```
mixcr exportClones -aaFeature 'FR4(0,-2)' ...
```
don't forget single quote mark.

**Comment by nathaniel-jd** [comment]
Good to know - thanks!
