### ISSUE TITLE
Analyze shotgun: difference between --do-not-extend-alignments and --impute-germline-on-export?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#450]
Hello - for analyze shotgun, i see there are two parameters: --do-not-extend-alignments and --impute-germline-on-export.  If I understand the extend comment correctly, these both appear to be ways to control whether 'extend' is run.  Is there some subtle difference between what each does?  Thanks.

**Comment by PoslavskySV** [comment]
Hi! Thanks for the question. There is a difference. 

`--do-not-extend-alignments` tells to skip `mixcr extend ...` step. The `extend` action transforms the raw TCR alignments using somewhat non-trivial  algorithm. This extended alignments are used then to build clones and further (optional) contig assembly. As result the use of `extend` may change e.g. clonotype frequencies. The main use case of `extend` is when you have very short reads (e.g. 40+40 rna-seq) and want to extract as much CDR3s as possible (so you extend good partial TCR CDR3s to full CDR3s).

On the other hand the option `--impute-germline-on-export` tells to use special preset for `exportClones`: `mixcr exportClones -p fullImputed ...`. This option doesn't change the raw alignments, so it has no any effect on the real clonotypes and the way they were computed: it just print germline sequences in export instead of uncovered target regions. The algorithm used for this is much simpler than the algorithm used in `extend`. The main use case of  `--impute-germline-on-export` is to properly export assembled contigs (`assembleContigs`), since each contig covers different gene features (so e.g. you have contig that covers a part of FR1 to the end of VRegion  and you use the option to see which part of FR1 is covered and which is not directly from the standard tsv output).

Hope I explained the difference) Anyway, I've opened a separate issue #453 since a detailed difference should be explained in the docs.

**Comment by dbolotin** [comment]
To sum up (draft for docs):

Both things: 

  - `extend` action, applied by default and skipped if `--do-not-extend-alignments` is specified, and
  - export options like `-nFeatureImputed ...` that are used instead of `-nFeature ...` if `--impute-germline-on-export` is specified

are doing approximately the same job with the following difference:

  - `extend` acts on the alignments or clonotypes files producing output in the same format thus allowing further processing with MiXCR (e.g. assembling clonotypes from extended alignments)
  - `-nFeatureImputed ...` / `-aaFeatureImputed ...` act on the export stage and applies the impute algorithm to the isolated TCR region (specified as parameter)

`extend` should be more robust, but, as a result it will skip more input sequences.

Hope my and Stanislav's explanations combined clarifies the whole idea. 😃

**Comment by bbimber** [comment]
Just to clarify: does extend simply act to complete the CDR3, or will extend actually build into the neighboring V and J regions?  

The reason I am interested is b/c complete or near-complete V/J coverage is important to us and one of the exciting new features in mixcr3.  I'm just trying to ensure we are running this in the optimal manner.  we have shotgun RNA-seq data (SMART-seq2 w/ Nextera fragmentation); however, typically 2x150bp reads.  Thanks.

**Comment by dbolotin** [comment]
By default `extend` tries to complete the CDR3, but this behaviour can be changed with `--v-anchor` and `--j-anchor` ([docs](https://mixcr.readthedocs.io/en/master/rnaseq.html#extend-action)), that set 3' and 5' boundary of the target region for extension.

**Comment by bbimber** [comment]
OK, thanks.  If I understand this correctly, it sounds like I would not want to change those?  Our goal is to assemble full-length V/J regions based on the sequence from each sample, not imputed values.  Therefore I think we would not want to use 'extend' on an overly large area.  Does this seem correct?

**Comment by dbolotin** [comment]
If the data covers whole full-VDJ region, you will get results without any imputation nether with `extend` nor with `--impute-germline-on-export`. In this case whole sequence will be assembled by the `assembleContigs` (requires `--assembleContigs` option)

On the other hand such data is very rare. `assembleContigs` uses reads assembled into the clonotype to extend its' sequence, thus it requires read to, at least partially, cover CDR3 (reads from `assemblePartial`). So, to cover full sequence one need a whole set of reads covering the V sequence with their R1 and CDR3 with R2. Or the other way around for FR4. And this is the only way to correctly reconstruct allelic/hypermutation SNPs for each particular clonotype, because CDR3 is the only part of the sequence that more or less uniquely identifies it.

So, if the goal is to collect a set of sequences for e.g. further synthesis and wet lab testing, and you can trade-off some inaccuracies in the sequence itself for the bigger number of the sequences with some imputation. If the goal is something similar to that, I recommend the following pipeline:
1. `mixcr align ...`
2. `mixcr assemblePartial ...`
3. `mixcr assemblePartial ...`
4. `mixcr extend ...` with default, CDR3 targeting options
5. `mixcr assemble -a ...`
6. `mixcr assembleContigs ...`
7. `mixcr extend --v-anchor L1Begin --j-anchor FR4End input.clns final.clns`

Steps from 1 to 6 can be executed with a single execution of `analyze shotgun` pipeline with `--contig-assembly` option.

You can then export clonotypes from both clns files before and after `extend`, and be able to calculate number of nucleotides imputed by the `extend` command (clonotypes in both files will have the same ordering). Based on this information you can control the number of the imputed nucleotides and e.g. take only sequences with no more than 20-30% of the imputed parts into further analysis / wet lab testing.

**Comment by bbimber** [comment]
OK, I believe I understand this better.  

This is a slightly tangential question, because you mentioned the requirement that the read pair span the CDR3.  Because we work in macaques, one of the general problems is an incomplete V-segment library (many animals have segments that different somewhat from the reference set).  If I simply wanted to reconstruct full-length V-segments from each subject using shotgun rna-seq libraries, are there ways to approach this with MiXCR that might be more effective than CDR3-based alignment?  I assume it would in theory be possible to run each tool using V-region or perhaps a sub-feature of V-region?  Do you have experience with anything like this?  If we do not include the CDR3 it would certainly be possible to have reads from different clones combined; however, I would imagine that is less of a concern if we are only trying to reconstruct the V-segment by itself?  Thanks.
