### ISSUE TITLE
How to explore cluster of total sequence of known clonedId

### ISSUE THREAD

**Issue by BlingArida** [milaboratory/mixcr#480]
Dear,
We are interested in retrieving full-length V/D/J sequences from high frequency clones. Our data are MiSEQ 2*300bp mRNA sequecing data.
My understanding is that clonal sequences which are very similar will be clustered together after alignment, and a "consensus" sequence will be used. 

I want to export all DNA sequence of one clondId to explore further research. Just like:
cloneId Chains  cloneCount     
0       IGH     6975.0  

I want to export all 6975 clone sequences which assemble target clonotype.

But from the exportClones function:
"mixcr exportClones -cloneId -chains -count -fraction -vGene -jGene -dGene -cGene -nFeature CDR3 -aaFeature CDR3 -lengthOf CDR3 -nFeatureImputed VDJRegion clones.clns -f cloneresult.xls
",only the "head" sequence export.
And I tried to use exportReadsForClones,just like this "mixcr exportReadsForClones --id 0 -s clones.clna cloneID",but the results are extract the original reads.

Is there anything I'm not doing right? Which function of MiCXR can help me to get the results?
Thank you very much!

Best regards,
Bling Arida

**Comment by PoslavskySV** [comment]
Dear Arida,

In order to export all reads which correspond to a specific clone you can use `exportReadsForClones ` ([see docs](https://mixcr.readthedocs.io/en/master/export.html#exporting-reads-aggregated-by-clones)).

By the way, MiXCR has built-in support for assembling of full TCR/Ig receptor sequences. You can find the docs here: https://mixcr.readthedocs.io/en/master/assembleContigs.html. To use it you can just pass `--contig-assembly` flag to [`analyze` command](https://mixcr.readthedocs.io/en/master/analyze.html) (and optionally add `--impute-germline-on-export`).

**Comment by PoslavskySV** [comment]
Sorry, I missed that you've already tried `exportReadsForClones`. 

If you need to export just the `clonalSequence` of each read that was aggregated by clone you can use the following approach. Suppose your clonal sequence is CDR3. Then you can use `exportAlignments` command on the `.clna` file like this:

```
mixcr exportAlignments -cloneId -nFeature CDR3 [other_options_you_need] clones.clna table.tsv
```

Then you can filter the table (using e.g. python or R)  to leave only `cloneId` that you need.

**Comment by BlingArida** [comment]
Dear Poslavsky，
Thanks a lot!
As you mentioned，I need to export the assembling of full TCR/Ig receptor sequence of each read that was aggregated by clone.
And I have tried codes as follows :
```
mixcr assemble --write-alignments --report report.txt alignments_rescued_2.vdjca clones.clna
mixcr assembleContigs --report report.txt clones.clna full_clones.clns
mixcr exportClones -c IG -p fullImputed full_clones.clns full_clones.xls
mixcr exportAlignments -cloneId -aaFeature CDR3 -nFeature CDR3 -nFeatureImputed VDJRegion clones.clna -f table.tsv
```
The option "-nFeatureImputed VDJRegion " that I tried to export the full assembling of full TCR/Ig receptor sequences,and I got "table.tsv".  According to the result, I calculate the clones by the statistical number of rows which is 8936 . This is a different number than the one MixCR gave me before.

cloneId Chains cloneCount
0 IGH 6975.0

And I can see many a lot of empty lines in the column of  "nFeatureImputed", just extract the column of  "nFeatureImputed" and calculate the number of rows which is 5466.
So,could you please tell me that how you calculate the cloneCount？And， is there anything wrong in the code that I used to export the full assembling of full TCR/Ig receptor sequences？
Thank you very much！

Best regards,
Bling Arida

**Comment by BlingArida** [comment]
> Dear Arida,
> 
> In order to export all reads which correspond to a specific clone you can use `exportReadsForClones ` ([see docs](https://mixcr.readthedocs.io/en/master/export.html#exporting-reads-aggregated-by-clones)).
> 
> By the way, MiXCR has built-in support for assembling of full TCR/Ig receptor sequences. You can find the docs here: https://mixcr.readthedocs.io/en/master/assembleContigs.html. To use it you can just pass `--contig-assembly` flag to [`analyze` command](https://mixcr.readthedocs.io/en/master/analyze.html) (and optionally add `--impute-germline-on-export`).

**Comment by PoslavskySV** [comment]
So, from your commands I see that you assemble clonotypes by CDR3, and then you want to look `VDJRegion` (if read covers it or imputed with germline?) of each sequencing _read_ aggregated into unique CDR3 clone --- is that what you mean? 

The complete description of `assemble` you can find here: https://mixcr.readthedocs.io/en/master/assemble.html. The clone count is not just the number of reads since mapping of low quality reads and clustering correct this value. You can turn off mapping using `-OmaxBadPointsPercent=0 ` and count clustered reads using `-addReadsCountOnClustering=true`: this  way the number of reads will be equal to clone count. Empty line in `-nFeatureImputed VDJRegion` means that either read does not cover `CDR3` (for reads that were not attached to any clone)  or that the read only partially covers `VDJRegion` and it is not possible to unambiguously impute germline sequence (e.g. different features were aligned to different genes etc.).

BTW, you can use `-cloneIdWithMappingType` to see how exactly read was attached to the clone (core/mapped/clustered etc).

**Comment by BlingArida** [comment]
Thank you very much for your timely reply. I will try the operation under your guidance!

**Comment by dbolotin** [comment]
Closing the issue as the problem seems to be resolved.

**Comment by BlingArida** [comment]
Dear Poslavsky，
Thanks a lot for your prompt reply!
I tried the commands that you gived. After a few days learning, I still have some questions.Could you please help me get further understanding?

According to [assmbleContigs](https://mixcr.readthedocs.io/en/master/assembleContigs.html)  
> use the option -p fullImputed in exportClones. With this option the germline nucleotide sequences will be used for uncovered regions of gene features (marked lowercase).  

 My understanding is that clonal sequences which are aligned to Germline V(D)J segments,then identifing the CDR3 sequences and clustering clones.So the <table><tr><td bgcolor=gray> -nFeatureImputed VDJRegion</td></tr></table> means if assmbled sequences covers CDR3 sequences but they not aligned well to Germline V(D)J segments，MiXCR will use  germline nucleotide sequences (marked lowercase) to replace the uncoverged regions. Is that correct?

Another quetion is  "Clustering sequences into clonal groups", I was wondering that if you just use ambiguous V gene and J gene calls when grouping similar sequences?

Thanks for your help.

Best regards,
Bling Arida
