### ISSUE TITLE
Unmatched arguments: extendAlignments

### ISSUE THREAD

**Issue by jasonsaunderswilliams** [milaboratory/mixcr#568]
Hi,

I can't see that anyone else has experience this issue. I'm using this manual (https://readthedocs.org/projects/mixcr/downloads/pdf/master/). I'm on the third step (4.3.4 Analysis of RNA-Seq data). 

I'm running MiXCR through a docker container:

```
docker run -ti --rm -v /data/Jason:/data/Jason -v /data/Jason:/inputfiles milaboratory/mixcr mixcr extendAlignments /inputfiles/4046alignmentsRescued_2.vdjca /inputfiles/4046alignmentsRescued_2_extended.vdjca
Unmatched arguments: extendAlignments, /inputfiles/4046alignmentsRescued_2.vdjca, /inputfiles/4046alignmentsRescued_2_extended.vdjca
Did you mean: filterAlignments or alignmentsStat or mergeAlignments?
```
I didn't mean any of the suggestions and was simply following the manual. 

Any help to solve this problem would be greatly appreciated.

By the way, great program and will be extremely useful for us. 

Best wishes,

Jason

**Comment by dbolotin** [comment]
Sorry, this part of documentation was not change when we renamed this action. Please use `extend` instead of `extendAlignments`.

Another suggestion is to use `mixcr analyze shotgun` (see [here](https://mixcr.readthedocs.io/en/master/analyze.html#analysis-of-non-enriched-or-random-fragments)) instead of running each command separately.

**Comment by PoslavskySV** [comment]
Documentation is correct. In MiXCR 2.x it was `extendAlignments`, which was replaced with universal `extend` in MiXCR 3.x.
