### ISSUE TITLE
MIXCR AIRR compliance

### ISSUE THREAD

**Issue by mikessh** [milaboratory/mixcr#571]
Formal checklist for AIRR-compliant software is here:
http://docs.airr-community.org/en/stable/swtools/airr_swtools_checklist.html

Support the format described at
http://docs.airr-community.org/en/stable/datarep/rearrangements.html. See https://github.com/airr-community/airr-standards for details.

IMHO the most laborious thing is to implement additional mutation format that follows CIGAR string (likely at the milib side).

**Comment by mikessh** [comment]
Also, do we "include a summary of the run parameters" in MIXCR report log?

**Comment by javh** [comment]
I'm in the process of updating the Rearrangement support table here:
https://github.com/airr-community/airr-standards/pull/428

Which we (DataRep WG) have been admitted slow to update since the original publication (Table 1):
https://www.frontiersin.org/articles/10.3389/fimmu.2018.02206/full

It looks like what we have currently listed for MiXCR is incorrect. We  have MiXCR support labeled as included in v2.2.1, which was the target release from the publication review stage.

Should we add a new target release number to the table? Remove MiXCR for now? What would you prefer?

Also, regarding the CIGAR strings, all of the required fields except `sequence_id` are technically nullable in the Rearrangement schema. The columns have to be in the TSV, but they can be populated with an empty string if the tool doesn't provide the information.  Populating all of the required fields is recommended, but isn't strictly necessary if a particular field is barrier to implementation.  The various `_start` and `_end` fields cover the most important information the CIGAR strings, so including those optional columns is a good alternative if it's easier to implement.

If there's any way I can help, let me know.

**Comment by PoslavskySV** [comment]
Hi, 

thanks for writing us. In fact everything is almost ready in MiXCR to support AiRR format, so we just need to release this functionality. We will do that within 2 weeks, that will be MiXCR v3.0.14, so you can update the release number to 3.0.14.

**Comment by javh** [comment]
That's great! Thanks, @PoslavskySV. I will update the AIRR-C documentation accordingly.

**Comment by bcorrie** [comment]
Hi Mike, others,

Has there been a version of MiXCR that supports the AIRR format as output? I see the discussion from last year, but I don't see any documentation on the current site that talks about AIRR support. On the docs site I don't see any thing about v3.0 revisions. I see master (which is v3 I think) but no minor revisions.  Am I missing something?

**Comment by PoslavskySV** [comment]
@bcorrie Hi Brian,

this feature is almost implemented internally, but we can't find time to polish it and release - so it is not released yet. Hope we'll finally do this in March.

**Comment by bcorrie** [comment]
Thanks for the update - looking forward to the capability.

**Comment by kira-neller** [comment]
Hi, I'm wondering if there are any updates on this capability? Thanks!

**Comment by shuchaa** [comment]
> Hi,
> 
> thanks for writing us. In fact everything is almost ready in MiXCR to support AiRR format, so we just need to release this functionality. We will do that within 2 weeks, that will be MiXCR v3.0.14, so you can update the release number to 3.0.14.

As other tools have long since (in terms of years) complied with the AIRR standards, I wanted to ask what is the ETA for version 3.0.14? Will it take another year?

**Comment by PoslavskySV** [comment]
Hi,

we just released [MiXCR v4.0](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0)

regarding the AIRR format, please see this [example](https://github.com/milaboratory/mixcr/wiki/Export-of-AIRR-formatted-tsv). Please note, that most probably you also should give repseqio exported reference library if you e.g. use immcantation pipeline to set both software packages in sync regarding the germline segment sequences and their markup.

**Comment by javh** [comment]
That's fantastic news! Thanks, @PoslavskySV. I'll update the AIRR Standards table accordingly.
