### ISSUE TITLE
What are "absence of CDR3 parts"?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#584]
Hi,
We noticed on the alignmentReport.log that,
`Total sequencing reads`=`Successfully aligned reads`+`Alignment failed, no hits (not TCR/IG?)`+`Alignment failed because of absence of CDR3 parts`.

I believe the `Successfully aligned reads` will be generated into VDJCA file. When we use `mixcr exportAlignmentsPretty` to export VDJCA file, we can see some reads with successfully aligned D and J but without V parts. So those reads are missing CDR3 parts due to no V part (absence of CDR3 parts).

So, my question is, what's the difference between `Alignment failed because of absence of CDR3 parts.` which is not in the VDJCA file and the reads in the VDJCA file which are absence of CDR3 parts?

P.S. We used the default alignment command.

Thanks!

**Comment by PoslavskySV** [comment]
`Alignment failed because of absence of CDR3 parts` means alignments which do no cover any part of CDR3, they can't be used in `assemble` in any way.

On the other hand there is a field `No CDR3 parts alignments, percent of successfully aligned`, which means alignments that do not cover both `VEnd` and `JBegin` reference points at the same time, but still cover some part of CDR3; they are  written to `.vdjca` file. They can be productive in `assemble` with e.g. `-OassemblingFeatures=CDR3(3,-3)`.
