### ISSUE TITLE
what's the definition of lack of a clone sequence?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#615]
it's a multiplexed pcr +DNA IGK library.
> Reads dropped due to the lack of a clone sequence, percent of total: 45217 (0.63%) [CDR3]
As the log mentioned above, it has dropped 45217 reads. So we deep analyzed the sample and found that, 
there are 27280 reads lack of IGKJ and 227 reads IGKV-IGLJ chimeras sequences. So those sequences are lack of CDR3. But totally only 27507 reads. I want to know what else reads have been dropped?

The reason I'm asking is after alignment, we have mapped IGK chains: 165187 (93.48%) but after clone assemble, we only have 88791 total IGK reads in the final export data. I'm curious what sequences have been dropped.

Thanks!

**Comment by arnavaz** [comment]
Hi MIXCR team,
We have a series of fastqs containing Unique Molecular Identifiers (UMIs). These fastqs are from hybrid-capturing of CDR3 regions of TCR (genomic DNA).
Since troubleshooting of the pipelines related to UMI-incorporated reads is not fully done yet, we have, for now, decided to remove the UMIs from the fastqs and then feed fastqs to the MIXCR for TCR analysis.
UMIs are therefore removed from the fastq reads and are tagged to the header of each line.
However, after feeding the fastqs with removed UMIs to MIXCR, the number of TRA and TRB clonotypes that we get are significantly decreased compared to the samples we’ve been doing MIXCR on before (samples that didn’t have UMIs and therefore fastqs were fed to MIXCR with no changes).
After doing a quick QC, we noticed that for fastqs with removed UMIs, the percentage of “Reads dropped due to the lack of a clone sequence” has significantly increased (in some cases pretty close to 100%).
We are therefore trying to find a reason for this. There was a similar question on your github and you’ve mentioned that it’s either library prep or data.
If we assume that library prep have been done properly, one of the problem with the data could be the removal of UMIs from the fastqs.
In the attachment 

you can see the similar lines of fastqs, before and after UMI removal. As you can see, UMIs are added to the headers and change them. Is there any chance that this is affecting the mixcr output? Does MIXCR read the headers?
[mixcr_example_UMI.txt](https://github.com/milaboratory/mixcr/files/5386261/mixcr_example_UMI.txt)

**Comment by PoslavskySV** [comment]
Hi,

native support of UMIs is introduced in [MiXCRv4](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0).

Best,
Stan
