### ISSUE TITLE
SMARTer Mouse TCR a/b Profiling Kit analysis options

### ISSUE THREAD

**Issue by paolo-kunderfranco** [milaboratory/mixcr#621]
Dear All,

I am trying to analyze with the following kit TCR data.
[https://www.takarabio.com/learning-centers/next-generation-sequencing/technical-notes/immune-profiling/tcr-repertoire-profiling-from-mouse-samples-(bulk)](url)

Could you please help me to set: 

--5-end option

--3-end option

--adapters option

Any other suggested parameter to add?

Many Thanks
Paolo

**Comment by T0dd0** [comment]
Hey Paolo,

since you are using a 5' RACE-amplification the option to go with would be "no-v-primers". You can find other options in the well written manual (https://mixcr.readthedocs.io/en/master/analyze.html). For the the 3' primer we use "c-primers". I don't know which one you are using but it should be easy for you to find out in which region your 3' primers bind. 
Adapters present or not depends on your method of sequencing. We use Illumnia, which utilizes adapters therefore the option we go with is "adapters-present".

Regards,
Thorben

**Comment by PoslavskySV** [comment]
@T0dd0  thanks for the answer!
