### ISSUE TITLE
Running MiXCR on single-end RNA-seq reads

### ISSUE THREAD

**Issue by jorisvdhaar** [milaboratory/mixcr#630]
Hi,

I have 65bp single-end bulk RNA sequencing data of tumors and would like to run mixcr to profile gamma and delta chains. In the publication, the performance of mixcr is assessed for 50bp paired-end reads, but I haven't seen performance stats for (relatively short) single-end sequencing. Can mixcr be run using this input data and if so, do you have any intuition about the reliability of the results?

Best wishes,

Joris

**Comment by Varix** [comment]
I don't think anyone monitors this issue tracker Joris....

**Comment by PoslavskySV** [comment]
In fact we monitor, but, unfortunately, we do not have enough time to provide a long answers in order to address the raised questions correctly. So in this tracker we focus on bug reports and feature requests, and If you use our Issue Template to file an issue, it will have a high chance to be answered quickly.

**Comment by Varix** [comment]
A great point. Something @jorisvdhaar probably would have liked to know 4 months ago, but very valid.

**Comment by PoslavskySV** [comment]
Hi,

support of single-cell analysis is introduced in [MiXCR v4](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0).

Best,
Stan
