### ISSUE TITLE
issue on Mixcr 3.0.6: clonotype disappear after merge two sequencing batches data

### ISSUE THREAD

**Issue by shine333** [milaboratory/mixcr#644]
Hi,
I'm working on a project analyzing TCR-seq data using the MIXCR3.0.6 , and I met some trouble.
I have samples with resequencing data using the same cDNA library, we have merged the two sequencing raw fasta file, performed cleaning and then mixcr pipeline, all codes are same, but the clonotypes seems so different before and after merging.
The parameters I used in mixcr :

java -Xmx20g -Xms5g -jar $mixcr align -t 20 -f -s hsa -p default -OallowPartialAlignments=true --report alignmentReport.log -OvParameters.parameters.mapperKValue=3 -OvParameters.parameters.minAlignmentLength=50 -OminSumScore=350 -OvParameters.parameters.maxAdjacentIndels=4 -OjParameters.parameters.mapperKValue=3 -OjParameters.parameters.maxAdjacentIndels=3 -OjParameters.parameters.absoluteMinScore=170 -OdParameters.geneFeatureToAlign={DBegin:DEnd} -OjParameters.geneFeatureToAlign={JBegin:FR4End} -OvParameters.geneFeatureToAlign={FR1Begin:VEnd} -OjParameters.parameters.minAlignmentLength=30 ${dir}${file}.clean_R1.fq.gz ${dir}${file}.clean_R2.fq.gz ${file}.vdj

java -Xmx20g -Xms5g -jar $mixcr assemble -f --report assemble.log -OcloneFactoryParameters.dParameters.absoluteMinScore=10 -OcloneFactoryParameters.jParameters.relativeMinScore=0.95 -OseparateByJ=true -OseparateByV=true ${file}.vdj ${file}.clns

java -Xmx4g -Xms3g -jar $mixcr exportClones -o -t -f -c TRB ${file}.clns ${file}.txt

The baches I used to make a contrast are:
s1:first sequecing clonotypes exported by mixcr;
s2:second sequencing clonotypes exported by mixcr;
he:merged sequencing clonotypes.

I have extracted the top1000 clonotypes from each batch, and make scatter plots to see the clonotype frequency distribution among the batches.As you can see from plots of one sample, many clonotypes are absent in different batches. I have no idea how did this happen.Is it the parameter setting problem?
![image](https://user-images.githubusercontent.com/35245100/112446405-1eb3c300-8d8b-11eb-935c-ea0980cb2ad0.png)
![image](https://user-images.githubusercontent.com/35245100/112446440-296e5800-8d8b-11eb-893f-88c29db70af9.png)
![image](https://user-images.githubusercontent.com/35245100/112446463-30956600-8d8b-11eb-97af-30fb1c5dab2a.png)
All the best,
Shine

**Comment by PoslavskySV** [comment]
Hi,

one possible reason is that the clustering, performed by the assembler, is more "aggressive" for the merged dataset, because more minor clonotypes passes the`clusteringFilter.specificMutationProbability` threshold. For example: suppose in dataset_1 you have clone A with count 10 and clone B with count 10 which differs only in one letter, and in dataset_2 you have clone A with count 10000; then in the merged dataset clone B will be clustered and disappear in the final output.

You can find the details [here](https://mixcr.readthedocs.io/en/master/assemble.html) and [here](https://www.nature.com/articles/nmeth.3364).
