### ISSUE TITLE
FASTQ files split by lane

### ISSUE THREAD

**Issue by f6v** [milaboratory/mixcr#669]
Hi,

I have a number of fastq files for one sample, split by lane. Would you generally recommend to merge them before running `shotgun` workflow? Or to analyse each lane and merge the results later?

Thanks!

**Comment by PoslavskySV** [comment]
Hi,

for running shotgun it is better to merge, since the clonotype assembly needs all data to correctly assemble clones. On the other hand, you can use the [align/assemble](https://mixcr.readthedocs.io/en/develop/rnaseq.html) pipeline manually, and in that case you can align fastq files independently  and merge them before `assemblePartial` using `mixcr mergeAlignments ...`.
