### ISSUE TITLE
Using MiXCR to reconstruct clonotype information from 10X scRNA-seq data

### ISSUE THREAD

**Issue by svalkiers** [milaboratory/mixcr#672]
Hi,

I am trying to reconstruct clonotype information from a 10X Genomics scRNA-seq run (without dedicated V(D)J amplification). I was wondering whether this would be possible with MiXCR. I have a couple of questions:

(1) Is the `analyze shotgun` command appropriate for this task?
(2) Is it possible to extract clonotypes from the BAM file in the Cell Ranger object or does this require a different input format?

Thank you for considering my questions.
Kind regards,
Sebastiaan

**Comment by Alex-Davydov** [comment]
Hi Sebastiaan,
1. For 10x 5' mRNA libraries yes, you can try `analyze shotgun`, but for 3' libraries there will be very few extracted TCRs or even nothing, because CDR3 is quite distant from the 3' end.
2. This option will be available in version 4.0.0 at the beginning of next year (January or February).
Best regards,
Alex

**Comment by PoslavskySV** [comment]
Hi,

we released  [MiXCR v4.0](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0) which fully supports single cell analysis. For 10x example see here: https://github.com/milaboratory/mixcr/wiki/Analysis-of-10X-Single-Cell-data

Best,
Stan
