### ISSUE TITLE
Enhancing outputs compatibility 

### ISSUE THREAD

**Issue by omegahh** [milaboratory/mixcr#773]
It seems like the MiXCR outputs, especially for .vdjca and .clnx files, do not fit the MiXCR program.

For example, I ran alignment using the MiXCR 4.0 release downloaded from GitHub. Then I change MiXCR to 4.0.0-55-develop after a email request for avoiding some other bugs. In this case, if I want to run `mixcr exportQc *.vdjca`. It will cause an exception: 

> Error while running command (com.milaboratory.mixcr.cli.qc.CommandExportQcAlign@19e7a160): java.lang.RuntimeException: Unsupported file format; .vdjca file of version MiXCR
.VDJC.V16 while you are running MiXCR MiXCR.VDJC.V17

The problem could be fixed if I re-run alignment with the new MiXCR 4.0.0-55-develop

**But a worse situation is that the outputs, which are generated by the same MiXCR program, is not compatible with some functions**

For example, I generated the *.clna files by the MiXCR 4.0.0-55-develop. It's ok when I run `mixcr postanalysis individual` while failed when I run `mixcr postanalysis overlap` or `mixcr exportClonesOverlap`. It will cause an exception:

> Error while running command (com.milaboratory.mixcr.cli.CommandExportOverlap@2bfbffb2): java.lang.RuntimeException: Unsupported file format; .clns file of version MiXCR.CLNA.V07 while you are running MiXCR MiXCR.CLNS.V12

Is there any possible to make the related outputs files be stable in formats for compatibility sake? At least in the same version of MiXCR program.

**Comment by PoslavskySV** [comment]
Hi,

due to many crucial fixes, enhancements and major new functions, backward incompatibility is introduced between MiXCR 4.0 and 4.1. Develop builds between 4.0 and official release of 4.1 are not stable and may be incompatible between each other.

Apologies for this inconvenience. MiXCR 4.1 will be released by the end of September, and we expect that further 4.x versions will be backward compatible with 4.1 (we had the same for MiXCR 3.x series, when we had to introduce backward incompatibility between 3.0 and 3.1 due to many improvements and changed implemented in 3.1 based on the feedback from the community after major 3.0 release).

**Comment by PoslavskySV** [comment]
[MiXCR v4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.0) released, docs updated.
