### ISSUE TITLE
Leader sequence and C gene in assembleContigs

### ISSUE THREAD

**Issue by mehdiborji** [milaboratory/mixcr#847]
I have long-read data on TCR/BCR full length mRNA. I would like MiXCR to include in the contig assembly the full coding part of chains. Using default options I can only see it starting from FR1. What options should I change it for that?

**Comment by mizraelson** [comment]
Hi,
Can you please tell more about the data structure. Do you have short reads randomly cover the full TCR/BCR gene region or do you have a pair of long reads that cover it fully?

**Comment by mehdiborji** [comment]
> Hi, Can you please tell more about the data structure. Do you have short reads randomly cover the full TCR/BCR gene region or do you have a pair of long reads that cover it fully?

As suggested these are full length nanopore data from 5' single cell data. I also have UMI and cell barcode for them which can be used for error correction, although I currently call clones in bulk fashion first.

I just need the options I need to use so that sequences before FR1 is included in the export clones function. Currently I only see FR1 to CDR3 direction.

**Comment by PoslavskySV** [comment]
Regarding Constant region - currently `assembleContigs` do not support C region, so it will be always missing after `assembleContigs`. Since it is rather conservative, one possibility is to use germline data with MiXCR imputation option on export. Regarding Leader sequence, it should work.

@dbolotin please comment

**Comment by dbolotin** [comment]
Hi, actually with default setting both sequences should be there, C gene will just not be aligned. Anyway I strongly suggest using using CELL and UMI barcodes for the analysis, because it should definitely increase the quality of sequences. We will be happy to help you setting up mixcr pipeline for the wet-lab protocol you have, for that please contact us at support@milaboratories.com or point us to the paper describing the library structure, if it is a published protocol.

**Comment by PoslavskySV** [comment]
Feel free to reopen if the issue is not resolved yet.

**Comment by PoslavskySV** [comment]
FYI: we'd added dedicated preset for high error Nanopore data in v4.2:

https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/#oxford-nanopore-technologies

(however if you have a custom architecture with cell and umi barcodes, one need to modify preset to take into account them)
