### ISSUE TITLE
get too few clones form whole genome sequencing data

### ISSUE THREAD

**Issue by Echoloria** [milaboratory/mixcr#863]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by Echoloria** [comment]
Hi,
   I'm trying to get TCR/BCR clones from whole genome sequencing(WGS) data (the sequening depth is about 30x ). However, I only got 7 TCR clones, here is my code:
 java -jar mixcr.jar analyze shotgun --species hsa --starting-material dna /data/R1.fastq.gz /data/R2.fastq.gz ./test

So, I just wonder why I got so few clones, I believe there are more TCR clones to be identified by mixcr, is there any way to dig more clones from the WGS data? Thanks.

Echo

**Comment by PoslavskySV** [comment]
Hi Echo,

Can you paste `mixcr` reports here? it's pretty standard to have just a few productive TCR rearrangements in the WGS data, depending on the source of cells.

**Comment by Echoloria** [comment]
Here are my two reports from two samples as attachment, thanks.
[A72.report.txt](https://github.com/milaboratory/mixcr/files/9946038/A72.report.txt)

[X53.report.txt](https://github.com/milaboratory/mixcr/files/9946040/X53.report.txt)

**Comment by PoslavskySV** [comment]
What was the read length?

**Comment by Echoloria** [comment]
We used PE150, so the length of each read is 150.

**Comment by Echoloria** [comment]
And the sample source we used is blood, as we all know, T cells are the most abundant in the PBMC, and we used highly deep sequencing methods(30X), so, I think there must be more clones than I have found.

**Comment by dbolotin** [comment]
Dear @Echoloria,

Here is my approximate estimation of a maximum possible yield of CDR3s from your data.

There are two chromosomes in each cell.

For each B- or T-cell there must exist two productive CDR3s, each on corresponding chromosome (i.e. TRB+TRA or IGH+IGL), the second chromosome for each gene may also contain the productive rearrangement, I can't find the numbers for this in the literature, but let's assume that 50% of the cells contain two mature rearrangements for a specific gene type.

The content of lymphocytes we are interested in is 60% T-cells + 10% B-cells = 70% in total (according to [wiki](https://en.wikipedia.org/wiki/Peripheral_blood_mononuclear_cell)).

With 30x coverage we then can make the following calculations:

```
  30 
  * .7 [T+B content] 
  * 2 [genes per cell; i.e. TRA+TRB] 
  * 0.75 [because in 50% of cases only one chromosome contain the V(D)J rearrangement] 
  = 31.5
```
, so `31.5` is a theoretical limit for the number of CDR3s across all genes that can be recovered

You have 23 and 21 CDR3s recovered (including low quality reads) for X53 and A72 correspondingly. Calculated as `Reads used in clonotypes` + `Reads dropped due to failed mapping`. Those numbers seems to be in a good agreement with my estimation (taken into account it's approximate nature).

The following factors may significantly affect my calculations:

  - the T+B content in PBMC may be lower, according to some sources T-cell content can be as low as 45% and B-cell content as low as 5% ([link](https://stemexpress.com/peripheral-blood-mononuclear-cells/))
  - due to uneven WGS coverage and low sequencing quality, corresponding regions may have less than 30x coverage
  - I might overestimated the share of cases in which there is a second mature V(D)J rearrangement for TCR/BCR genes

You can try the following things to increase this number, but anyway, I don’t think you can get more than 5-7 new CDR3s:

  - trim Illumina adapters before mixcr analysis
  - trim low quality by specifying the following options on the align step `--trimming-quality-threshold 11 --trimming-window-size 7`
  - turn off quality aware error correction by adding this `-ObadQualityThreshold=0` to the assemble command (though, I don’t recommend doing it)

All the best,
Dmitry.

**Comment by Echoloria** [comment]
Hi Dmitry,

     Thanks for your professional explanation, I think before I post these questions above, I didn't understand the meaning of 30x depth in WGS, now I have understand the principle of it, 30X depth WGS is not a propriate way to get BCR/TCR. Anyway,  I have learned a lot from this conversation, thanks again! And I'll close this issue.

Best wishes,
Echo

**Comment by mizraelson** [comment]
Just to emphasize on the meaning of 30x coverage so it is more clear. Lets assume we have 1000 full genome copies in the tube. For most of the genes their sequences are identical between different genome copies. When we sequence such library with 30x coverage it means that we get 30 reads per each base pair. However, these reads come from different genome copies, but since for the most part their sequences are identical - we say each region is covered 30 ish times (30x) and we can use these reads to correct the errors.
However, in case of TCR and BCR loci of the mature T and B cells - their sequences differ from cell to cell, from one genome copy to another. Thus, if we have 30x coverage, we get, theoretically, 30 reads that cover 30 CDR3 regions across all TCR/BCR genes of different cells, meaning we get 30 different CDR3s for every gene but **not** 30 reads per each CDR3. And, as Dmitry has pointed out above, this actual number is gonna be  somewhat lower.

**Comment by Echoloria** [comment]
> Just to emphasize on the meaning of 30x coverage so it is more clear. Lets assume we have 1000 full genome copies in the tube. For most of the genes their sequences are identical between different genome copies. When we sequence such library with 30x coverage it means that we get 30 reads per each base pair. However, these reads come from different genome copies, but since for the most part their sequences are identical - we say each region is covered 30 ish times (30x) and we can use these reads to correct the errors. However, in case of TCR and BCR loci of the mature T and B cells - their sequences differ from cell to cell, from one genome copy to another. Thus, if we have 30x coverage, we get, theoretically, 30 reads that cover 30 CDR3 regions across all TCR/BCR genes of different cells, meaning we get 30 different CDR3s for every gene but **not** 30 reads per each CDR3. And, as Dmitry has pointed out above, this actual number is gonna be somewhat lower.

Hey, mizraelson, thank you very much, you have explained the meaning of sequencing depth of WGS very clearly, thanks again.
